### ISSUE TITLE
Cannot build locally

### ISSUE THREAD

**Issue by mickaelistria** [OmniSharp/omnisharp-node-client#290]
```
Project OmniSharp.Nuget (.NETFramework,Version=v4.5.1) will be compiled because dependencies changed
Compiling OmniSharp.Nuget for .NETFramework,Version=v4.5.1
/home/mistria/git/omnisharp-node-client/vendor/omnisharp-roslyn/src/OmniSharp.Nuget/project.json(14,41): error NU1001: The dependency WindowsBase could not be resolved.

Compilation failed.
    0 Warning(s)
    1 Error(s)
```

Are there some requirements about dotnet or nuget version maybe?

**Comment by Markus-83** [comment]
I also cannot build the client locally.

I downloaded Release v5.2.0 and executed the steps under topic Developers, but the step "npm install fails".

OS: Windows 10 64-bit
Using VS Code 1.7.2

Output:
C:\Omnisharp\Client>npm install
npm WARN package.json Dependency 'mocha' exists in both dependencies and devDependencies, using 'mocha@^2.4.5' from dependencies
npm WARN engine strip-bom@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine vscode-jsonrpc@2.4.0: wanted: {"node":">=4.0.0 || >=6.0.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine decompress-targz@4.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine gulp-sourcemaps@2.2.1: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine gulp-tslint@6.1.3: wanted: {"node":">= 4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine decompress@4.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine decompress-unzip@4.0.1: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine decompress-tar@4.1.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine decompress-tar@4.1.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine decompress-tarbz2@4.1.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global tsd@0.6.5 should be installed with -g

> omnisharp-client@5.2.0 prepublish C:\Omnisharp\Client
> typings install && gulp npm-prepublish

typings WARN badlocation "github:david-driscoll/lodash-ts" is mutable and may change, consider specifying a commit hash
typings WARN deprecated 2016-09-26: "registry:env/mocha#2.2.5+20160321223601" is deprecated (updated, replaced or removed)
typings WARN deprecated 2016-11-05: "registry:env/node#4.0.0+20160507210304" is deprecated (updated, replaced or removed)


├── lodash
├── mocha (global)
└── node@4 (global)

[13:17:28] Using gulpfile C:\Omnisharp\Client\gulpfile.js
[13:17:28] Starting 'clean:lib'...
[13:17:28] Starting 'clean:test'...
[13:17:28] Finished 'clean:lib' after 41 ms
[13:17:28] Finished 'clean:test' after 23 ms
[13:17:28] Starting 'clean'...
[13:17:28] Finished 'clean' after 2.81 μs
[13:17:28] Starting 'typescript'...
[13:17:28] 'typescript' errored after 49 ms
[13:17:28] C:\Omnisharp\Client\node_modules\strip-bom\index.js:2
module.exports = x => {
                   ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Omnisharp\Client\node_modules\gulp-sourcemaps\src\init.js:10:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! omnisharp-client@5.2.0 prepublish: `typings install && gulp npm-prepublish`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the omnisharp-client@5.2.0 prepublish script 'typings install && gulp npm-prepublish'.
npm ERR! This is most likely a problem with the omnisharp-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install && gulp npm-prepublish
npm ERR! You can get their info via:
npm ERR!     npm owner ls omnisharp-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Omnisharp\Client\npm-debug.log

C:\Omnisharp\Client>

**Comment by mickaelistria** [comment]
Note that I'm on Fedora 25 using the dotnet core rpms.

**Comment by mickaelistria** [comment]
Seems out of date, I can build locally.
